### ISSUE TITLE
all done wtihout charset

### ISSUE THREAD

**Issue by steve02081504** [Taromati2/yaya-CI-check#2]
@ponapalt 
All the work is done
Except for a problem with the encoding conversion
See https://github.com/Taromati2/ghost/runs/3844006038?check_suite_focus=true for an example

I don't know how to fix this coding problem, so if you do please change the code or let me know
Otherwise in CI we can only use the error message in English

**Comment by ponapalt** [comment]
yaya::char_t = wchar_t.
You can ignore the charset setting and just convert the yaya::char_t (wchar_t) to UTF-8 in loghandler.

**Comment by steve02081504** [comment]
> 
> 
> yaya::char_t = wchar_t. You can ignore the charset setting and just convert the yaya::char_t (wchar_t) to UTF-8 in loghandler.

like https://github.com/Taromati2/yaya-CI-check/commit/12557c4ff5ac9c7fd46c1369c15af8ca61350a9b ?

**Comment by steve02081504** [comment]
https://github.com/Taromati2/ghost/actions/runs/1322327662
It looks like all the Chinese characters have turned into question marks

**Comment by ponapalt** [comment]
I think you can remove this problem as follows : just remove do_charset_convert and pass str to fwprintf directly.

**Comment by ponapalt** [comment]
Sorry, above solution is incomplete. Please check below URL.
https://blogs.osdn.jp/2020/04/24/wprintf.html
key point : _setmode(_fileno(stdout), _O_U8TEXT);

**Comment by steve02081504** [comment]
Ohhhhhhhhh It's working!
thanks

**Comment by steve02081504** [comment]
If you think there are function names that need tweaking just do it now, I think
Then we well ready to release the latest version of yaya!
